@TicketTypeWebAPI_HostAddress = http://localhost:5031

GET {{TicketTypeWebAPI_HostAddress}}/api/TicketType/
Accept: application/json

###
POST {{TicketTypeWebAPI_HostAddress}}/api/TicketType/
Content-Type: application/json
{
    "ticketTypeId": 5,
    "ticketTypeName": "System login error",
    "assignedToEmpId": 1,
    "priorityId": 1   
  }
###
POST {{TicketTypeWebAPI_HostAddress}}/api/TicketType/Employee
Content-Type : application/json
{
  "empId": 3
}
###
POST {{TicketTypeWebAPI_HostAddress}}/api/TicketType/TicketPriority
Content-Type : application/json
{
  "priorityId": 3
}
###
PUT {{TicketTypeWebAPI_HostAddress}}/api/TicketType/5
Content-Type: application/json
{
    "ticketTypeId": 5,
    "ticketTypeName": "System login error",
    "assignedToEmpId": 2,
    "priorityId": 2,
    "assignedToEmp": null,
    "priority": null
  }

###
GET {{TicketTypeWebAPI_HostAddress}}/api/TicketType/ByEmployeeId/2
Accept: application/json

###
GET {{TicketTypeWebAPI_HostAddress}}/api/TicketType/ByTypeId/2
Accept: application/json

###
GET {{TicketTypeWebAPI_HostAddress}}/api/TicketType/ByPriority/2
Accept: application/json
###


DELETE {{TicketTypeWebAPI_HostAddress}}/api/TicketType/FromTicketType/1
Accept: application/json

###
DELETE {{TicketTypeWebAPI_HostAddress}}/api/TicketType/FromEmployee/2
Accept: application/json

###
DELETE {{TicketTypeWebAPI_HostAddress}}/api/TicketType/FromPriority/1
Accept: application/json


